#!/usr/bin/env python3
"""Generate docs/skill-agent-model-matrix.md: the full skill -> agent ->
model-tier matrix for every skill file that declares a non-empty `agents:`
frontmatter field.

Why this exists (agent-to-skill migration plan, Phase 1): tools/skill-runner.sh
prints a skill's body verbatim with no mechanism to honor a referenced agent's
`model:` tier -- inlining a skill that names an opus-tier agent (e.g.
skills/engineering/review.md -> architect, model: opus) at a lower-tier
caller's session silently drops that capability upgrade. Before deciding how
widespread the problem is, the true scope has to be measured, not assumed --
an earlier draft of this plan named "5 files" from memory; this script proves
(or corrects) that count from the tree itself, every time it is run.

Scope note: the 15 problem-shaped skills under skills/*/SKILL.md route to
genius agents via a `shapes:` frontmatter field and a body table ("Relevant
geniuses"), not via `agents:` -- they carry no machine-readable agent list at
all, and their body already instructs an explicit
`tools/genius-invoker.sh invoke <agent>` step naming the spawn requirement.
They are therefore out of this matrix's scope by definition (no `agents:`
field to read) and out of tools/skill-runner.sh's fix surface (which can only
act on frontmatter it can parse) -- not because they are risk-free, but
because their invocation contract is already a different, explicit mechanism.

Usage:
  scripts/generate-skill-agent-model-matrix.py                    # regenerate docs/skill-agent-model-matrix.md
  scripts/generate-skill-agent-model-matrix.py --check             # exit 1 if the table is stale
  scripts/generate-skill-agent-model-matrix.py --repo-root <path>  # operate on a different repo root (tests)
"""
import argparse
import glob
import os
import re
import sys

AGENTS_BLOCK_RE = re.compile(r"^agents:\s*\n((?:\s*-\s*.+\n)*)", re.MULTILINE)
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
MODEL_RE = re.compile(r"^model:\s*(\S+)\s*$", re.MULTILINE)

# Ordinal ranking of model tiers, cheapest to most capable/expensive.
# source: ~/.claude/rules/agent-reference/effort-calibration.md model catalog
# (Anthropic claude-api reference, cached 2026-06-24).
TIER_RANK = {"haiku": 0, "sonnet": 1, "opus": 2, "fable": 3}
BASELINE_MODEL = "sonnet"  # matches tools/skill-runner.sh's ZETETIC_SKILL_BASELINE_MODEL default


def agent_model(repo_root, agent_name):
    for sub in ("agents", os.path.join("agents", "genius")):
        path = os.path.join(repo_root, sub, agent_name + ".md")
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                m = MODEL_RE.search(f.read())
                return m.group(1) if m else None
    return None


def is_escalation(model):
    if model not in TIER_RANK:
        return False
    return TIER_RANK[model] > TIER_RANK[BASELINE_MODEL]


def parse_agents_field(content):
    m = AGENTS_BLOCK_RE.search(content)
    if not m or not m.group(1).strip():
        return []
    return [
        line.strip().lstrip("-").strip()
        for line in m.group(1).splitlines()
        if line.strip()
    ]


def collect_rows(repo_root):
    rows = []
    pattern = os.path.join(repo_root, "skills", "**", "*.md")
    for path in sorted(glob.glob(pattern, recursive=True)):
        if os.path.basename(path).startswith("_"):
            continue
        with open(path, encoding="utf-8") as f:
            content = f.read()
        fm_match = FRONTMATTER_RE.match(content)
        if not fm_match:
            continue
        agents = parse_agents_field(fm_match.group(1))
        if not agents:
            continue
        relpath = os.path.relpath(path, repo_root)
        for agent in agents:
            model = agent_model(repo_root, agent)
            rows.append((relpath, agent, model or "UNRESOLVED", is_escalation(model or "")))
    return rows


def render(rows):
    lines = [
        "<!-- Generated by scripts/generate-skill-agent-model-matrix.py. Do not hand-edit. -->",
        "# Skill -> agent -> model-tier matrix",
        "",
        "Every `skills/**/*.md` file with a non-empty `agents:` frontmatter field, and every",
        "agent it names, cross-referenced against that agent's declared `model:` tier",
        "(`agents/*.md` and `agents/genius/*.md`). `Escalation` is true when the agent's tier",
        f"exceeds the baseline (`{BASELINE_MODEL}`) that `tools/skill-runner.sh` compares against by",
        "default -- exactly the condition under which the runner's model-tier escalation banner",
        "fires. Regenerate with `scripts/generate-skill-agent-model-matrix.py`; verify with `--check`.",
        "",
        f"Total skill files with a non-empty `agents:` field: **{len(set(r[0] for r in rows))}**. "
        f"Rows naming an escalation-tier agent: **{sum(1 for r in rows if r[3])}**.",
        "",
        "| Skill | Agent | Model | Escalation |",
        "|---|---|---|---|",
    ]
    for relpath, agent, model, escal in rows:
        lines.append(f"| `{relpath}` | `{agent}` | `{model}` | {'yes' if escal else 'no'} |")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--repo-root",
        default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..")),
    )
    args = parser.parse_args()

    rows = collect_rows(args.repo_root)
    rendered = render(rows)
    out_path = os.path.join(args.repo_root, "docs", "skill-agent-model-matrix.md")

    if args.check:
        if not os.path.exists(out_path):
            print(f"MISSING: {out_path} does not exist -- run without --check to generate it.", file=sys.stderr)
            return 1
        with open(out_path, encoding="utf-8") as f:
            existing = f.read()
        if existing != rendered:
            print(f"STALE: {out_path} does not match the tree -- regenerate it.", file=sys.stderr)
            return 1
        print(f"OK: {out_path} matches the tree ({len(rows)} rows).")
        return 0

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(rendered)
    print(f"Wrote {out_path} ({len(rows)} rows).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
