#!/usr/bin/env python3
"""Generate rules/skill-routing-table.md from the 15 problem-shaped skills'
`shapes:` frontmatter.

GOA-DESIGN.md (Phase 1 codegen note, lines 56-57 / 85-86): the shape-to-skill
mapping is "currently hand-wired, not learned" — today it lives only as prose
copied by hand into docs/goa-phase0/label-rubric.md's frozen shape catalog.
This script makes the mapping machine-readable: it reads `shapes:` frontmatter
declared on each `skills/*/SKILL.md` (one shape id per skill today; the field
is a list so a skill covering >1 shape needs no schema change) and emits a
single compact routing artifact, mirroring the existing agent-routing-table.py
pattern (rules/agent-routing-table.md) so routing consumers read a generated
table instead of grepping or hand-copying 15 files.

The 15 shape ids are exactly the 15 skill names — sourced from
docs/goa-phase0/label-rubric.md ("Assign to each case EXACTLY ONE label: one
of the 15 shape names below" — the shape catalog there is the skill
directory names verbatim).

Usage:
  scripts/generate-skill-routing-table.py                    # regenerate rules/skill-routing-table.md
  scripts/generate-skill-routing-table.py --check             # exit 1 if the table is stale
  scripts/generate-skill-routing-table.py --repo-root <path>  # operate on a different repo root (tests)
"""
import argparse
import glob
import os
import re
import sys


def frontmatter(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    block = m.group(1)
    fm = {}
    name_m = re.search(r"^name:\s*(.+)$", block, re.M)
    if name_m:
        fm["name"] = name_m.group(1).strip().strip('"')
    shapes_m = re.search(r"^shapes:\s*\[(.*?)\]\s*$", block, re.M)
    if shapes_m:
        fm["shapes"] = [s.strip() for s in shapes_m.group(1).split(",") if s.strip()]
    # description: is a YAML folded block (`>`) spanning indented lines until
    # the next top-level `key:` or the closing `---`.
    desc_m = re.search(r"^description:\s*>\s*\n((?:[ \t].*\n?)+)", block, re.M)
    if desc_m:
        desc_lines = [ln.strip() for ln in desc_m.group(1).splitlines() if ln.strip()]
        fm["description"] = " ".join(desc_lines)
    else:
        desc_m = re.search(r'^description:\s*"(.*)"\s*$', block, re.M)
        if desc_m:
            fm["description"] = desc_m.group(1).strip()
    return fm


def collect_rows(repo_root):
    rows = []
    for path in sorted(glob.glob(os.path.join(repo_root, "skills", "*", "SKILL.md"))):
        fm = frontmatter(path)
        if not fm or "name" not in fm or "shapes" not in fm:
            continue
        rows.append(fm)
    return rows


def build(repo_root):
    rows = collect_rows(repo_root)
    lines = [
        "# Skill Shape Routing Table — generated, do not edit",
        "",
        "Generated by `scripts/generate-skill-routing-table.py` from each",
        "problem-shaped skill's `shapes:` frontmatter (`skills/*/SKILL.md`).",
        "The shape ids are the 15 GOA shape names",
        "(`docs/goa-phase0/label-rubric.md`). Route from THIS table: match the",
        "problem against a shape id or its description, then use the named",
        "skill. Re-run the generator after any `shapes:` or `description:`",
        "frontmatter edit — CI's `--check` mode fails the build on drift.",
        "",
        "| Shape(s) | Skill | Description |",
        "|---|---|---|",
    ]
    for fm in rows:
        shapes_col = ", ".join(fm["shapes"]).replace("|", "/")
        desc_col = fm.get("description", "").replace("|", "/")
        lines.append(f"| {shapes_col} | {fm['name']} | {desc_col} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--repo-root",
        default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    args = parser.parse_args()

    out_path = os.path.join(args.repo_root, "rules", "skill-routing-table.md")
    content = build(args.repo_root)

    if args.check:
        on_disk = ""
        if os.path.exists(out_path):
            with open(out_path, encoding="utf-8") as fh:
                on_disk = fh.read()
        if on_disk != content:
            print(
                "rules/skill-routing-table.md is stale — run "
                "scripts/generate-skill-routing-table.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print("rules/skill-routing-table.md up to date")
        return

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)
    n = content.count("\n| ") - 1  # minus the header row
    print(f"wrote {out_path}: {n} shapes, {len(content)} bytes")


if __name__ == "__main__":
    main()
