#!/usr/bin/env python3
"""Inject the inline `<zetetic-spine>` block into every agent definition.

The zetetic spine (recall -> evidence/sources -> adversarial-verify -> remember)
is the per-task loop every agent runs. On-demand reference docs are NOT read
spontaneously, so the compact spine must live INLINE in each agent (present at
spawn). This generator is the single source for those inline blocks — it writes
into the repo's agent source files; `setup.sh` then copies them to ~/.claude/
verbatim. Never hand-edit an injected block; edit this generator and re-run.

The block is delimited by HTML comments so the generator can find-and-replace it
idempotently (2nd run on an already-injected file is a no-op). It is anchored
immediately after the agent's existing zetetic section: `</zetetic-standard>`
(team agents + feynman) or, failing that, `</zetetic>` (genius agents).

Calibration: research and epistemic agents treat `claude.ai Science` as
first-recourse for the evidence beat; all others carry it as awareness. The set
is editable below. Full rationale: memory/ADR-003-zetetic-spine-enforcement.md.

Usage:
  scripts/generate-spine.py            # inject/refresh the block in every agent
  scripts/generate-spine.py --check    # exit 1 if any agent's block is stale
"""
import glob
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN = "<!-- BEGIN ZETETIC-SPINE (generated by scripts/generate-spine.py — do not hand-edit) -->"
END = "<!-- END ZETETIC-SPINE -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# Research + epistemic agents: claude.ai Science is first-recourse for the
# evidence beat. Identified by agent `name` (slug). source: plan §Conventions
# confirmées + ADR-003.
STRONG = {
    # team — research-correlated (have or are about scientific evidence)
    "research-scientist", "data-scientist", "reviewer-academic",
    "paper-writer", "professor",
    # genius — epistemic reasoning patterns
    "popper", "cochrane", "feynman", "peirce", "fisher", "semmelweis",
}

# Deliberate exclusions — agents with no claim-making/testing/coding surface, for
# which the full spine would be process theater (Rational/Essential pillars: depth
# must be proportional). memory-writer is a 16K-budget scribe that already embodies
# the spine's discipline domain-specifically (it only persists WHY-level facts,
# verifies its write, and refuses to invent — its `<not provided by parent>` IS the
# "no source → say I don't know" rule). source: ADR-003.
EXCLUDE = {"memory-writer"}

# The evidence-beat resource clause differs by calibration only.
RESOURCE_STRONG = (
    "**For any scientific-claim component, `claude.ai Science` is your first "
    "recourse** (verify claim / audit ablation / bound thesis) before the "
    "primary paper, then WebSearch"
)
RESOURCE_STD = (
    "**When a task acquires a scientific-claim component, route this beat first "
    "to `claude.ai Science`** (verify / audit / bound)"
)


def spine_block(strong: bool) -> str:
    resource = RESOURCE_STRONG if strong else RESOURCE_STD
    return "\n".join([
        BEGIN,
        "<zetetic-spine>",
        "**Per-task spine — run in order; depth scales with stakes " +
        "(coding-standards.md §10): recall → evidence/sources → " +
        "adversarial-verify → remember.**",
        "1. **Recall** before acting — `cortex:recall` scoped to your " +
        "`agent_topic` + your memory scope. If recall contradicts the plan, " +
        "stop and reconcile before proceeding.",
        "2. **Evidence/sources** — *the source precedes the implementation, "
        "never the reverse.* Every claim, constant, threshold, and algorithm is "
        "**derived from** a source read first. A citation attached *after* the "
        "code — a paper picked because it resembles what you already wrote — is "
        "fabricated proof, not evidence; resemblance is not prescription, so "
        "verify the source actually states your value/equation and that its "
        "conditions match yours. No source → say \"I don't know\" and stop; do "
        "not ship, then justify (coding-standards.md §8). " + resource +
        " — `~/.claude/rules/agent-reference/research-resources.md`.",
        "3. **Adversarial-verify** before \"done\" — design the test that " +
        "catches the error *if it exists* (severity, not ceremony); reproduce " +
        "before claiming a fix. **For code changes at High/Medium stakes, prove " +
        "the suite KILLS mutants, not just covers lines** — mutation testing on " +
        "the changed lines (`tools/mutation_check.sh`; test-engineer Move 8 / " +
        "coding-standards.md §12): kill or document-as-equivalent every " +
        "survivor. Bound the thesis to its evidence regime.",
        "4. **Remember** after acting — persist WHY-level outcomes " +
        "(decision+rationale, rejected approach+root cause, benchmark deltas " +
        "before AND after); code stays in the repo.",
        "",
        "**Stamp the standard you were judged against.** Any rule-compliance " +
        "report you emit states the rules version it was evaluated under — " +
        "`tools/plugin-version-check.sh --rules-version` (and " +
        "`--version` for the plugin build). A compliance verdict read later is " +
        "uninterpretable without it, and a stale plugin can enforce a " +
        "superseded standard while certifying the result (issue #52).",
        "",
        "Failed gate ⇒ **STOP** and surface the gap; never paper over a missing " +
        "source with confidence. Full procedure: " +
        "`~/.claude/rules/agent-reference/zetetic-spine.md`.",
        "</zetetic-spine>",
        END,
    ])


def anchor_end(text: str):
    """Return the index just past the agent's zetetic-section closing tag, or
    None. Prefers `</zetetic-standard>`; falls back to `</zetetic>`. The two are
    distinct strings (`</zetetic>` is not a substring of `</zetetic-standard>`
    nor of `</zetetic-spine>`), so detection is unambiguous."""
    for tag in ("</zetetic-standard>", "</zetetic>"):
        i = text.find(tag)
        if i != -1:
            return i + len(tag)
    return None


def render(text: str, strong: bool):
    """Return (new_text, status). status in {'replaced','inserted','no-anchor'}.
    Idempotent: an already-current block yields new_text == text."""
    block = spine_block(strong)
    if BLOCK_RE.search(text):
        return BLOCK_RE.sub(lambda _m: block, text, count=1), "replaced"
    end = anchor_end(text)
    if end is None:
        return text, "no-anchor"
    new = text[:end] + "\n\n" + block + text[end:]
    return new, "inserted"


def agent_files():
    team = glob.glob(os.path.join(REPO, "agents", "*.md"))
    genius = glob.glob(os.path.join(REPO, "agents", "genius", "*.md"))
    for f in sorted(team) + sorted(genius):
        base = os.path.basename(f)
        if base in ("INDEX.md", "ROUTING.md"):
            continue
        yield f


def slug(text: str, fallback: str) -> str:
    m = re.search(r"^name:\s*(.+)$", text, re.M)
    return m.group(1).strip().strip('"') if m else fallback


def main():
    check = "--check" in sys.argv
    stale, changed, no_anchor = [], [], []
    for f in agent_files():
        with open(f, encoding="utf-8") as fh:
            text = fh.read()
        name = slug(text, os.path.splitext(os.path.basename(f))[0])
        if name in EXCLUDE:
            continue
        new, status = render(text, name in STRONG)
        if status == "no-anchor":
            no_anchor.append(name)
            continue
        if new == text:
            continue
        if check:
            stale.append(name)
        else:
            with open(f, "w") as fh:
                fh.write(new)
            changed.append(name)

    if no_anchor:
        print("WARNING: no <zetetic-standard>/<zetetic> anchor in: "
              + ", ".join(no_anchor), file=sys.stderr)

    if check:
        if stale:
            print("zetetic-spine block stale in %d agent(s): %s\n"
                  "run scripts/generate-spine.py"
                  % (len(stale), ", ".join(stale)), file=sys.stderr)
            sys.exit(1)
        print("zetetic-spine up to date in all agents")
        return
    print("zetetic-spine: updated %d agent(s)%s"
          % (len(changed),
             (" — no-anchor: %d" % len(no_anchor)) if no_anchor else ""))


if __name__ == "__main__":
    main()
