#!/usr/bin/env python3
"""Generate rules/agent-routing-table.md — the compact routing table.

One line per agent (name + trigger keywords + one-line description), generated
purely from agent frontmatter. Routing consumers (orchestrator, genius:route,
genius:index) read THIS file instead of the 132KB INDEX.md or full agent files.
Lives under rules/ (installed to ~/.claude/rules/) — NOT under agents/, where
Claude Code would parse it as a bogus agent definition.

Usage:
  scripts/generate-routing-table.py            # regenerate rules/agent-routing-table.md
  scripts/generate-routing-table.py --check    # exit 1 if the table is stale
"""
import re
import sys
import glob
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "rules", "agent-routing-table.md")


def frontmatter(path):
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for key in ("name", "description", "when_to_use", "model", "shapes"):
        km = re.search(rf"^{key}:\s*(.+)$", m.group(1), re.M)
        if km:
            val = km.group(1).strip().strip('"')
            while "\\u" in val or '\\"' in val:
                try:
                    decoded = val.replace('\\"', '"').encode().decode("unicode_escape")
                except UnicodeDecodeError:
                    break
                if decoded == val:
                    break
                val = decoded
            fm[key] = val.strip('"').strip()
    return fm


def row(fm, shapes_col):
    name = fm.get("name", "?")
    desc = fm.get("description", "").replace("|", "/")
    when = fm.get("when_to_use", "").replace("|", "/")
    trig = shapes_col.replace("|", "/") if shapes_col else when
    return f"| {name} | {trig} | {desc} |"


def build():
    lines = [
        "# Agent Routing Table — generated, do not edit",
        "",
        "Generated by `scripts/generate-routing-table.py` from agent frontmatter.",
        "Route from THIS table only: match the problem against trigger keywords and",
        "descriptions, then spawn the agent. Do NOT Read full agent files or",
        "`agents/genius/INDEX.md` to make a routing decision — INDEX.md is for",
        "human deep-dives and targeted `grep` (via `tools/shape-router.sh` /",
        "`tools/genius-invoker.sh route`), never a full-file Read.",
        "",
        "## Genius agents (route by problem shape)",
        "",
        "| Agent | Shapes (trigger keywords) | Description |",
        "|---|---|---|",
    ]
    genius = sorted(
        f for f in glob.glob(os.path.join(REPO, "agents", "genius", "*.md"))
        if not f.endswith("INDEX.md") and not f.endswith("ROUTING.md")
    )
    for f in genius:
        fm = frontmatter(f)
        if not fm or "name" not in fm:
            continue
        shapes = fm.get("shapes", "").strip("[]").replace(",", ", ").replace("  ", " ")
        shapes = re.sub(r"\s+", " ", shapes)
        lines.append(row(fm, shapes))

    lines += [
        "",
        "## Team agents (route by role + when-to-use)",
        "",
        "| Agent | When to use | Description |",
        "|---|---|---|",
    ]
    team = sorted(
        f for f in glob.glob(os.path.join(REPO, "agents", "*.md"))
        if not f.endswith("ROUTING.md")
    )
    for f in team:
        fm = frontmatter(f)
        if not fm or "name" not in fm:
            continue
        lines.append(row(fm, fm.get("when_to_use", "")))

    return "\n".join(lines) + "\n"


def main():
    content = build()
    if "--check" in sys.argv:
        if os.path.exists(OUT):
            with open(OUT, encoding="utf-8") as fh:
                on_disk = fh.read()
        else:
            on_disk = ""
        if on_disk != content:
            print("agent-routing-table.md is stale — run scripts/generate-routing-table.py", file=sys.stderr)
            sys.exit(1)
        print("agent-routing-table.md up to date")
        return
    with open(OUT, "w") as fh:
        fh.write(content)
    n = content.count("\n| ") - 2  # minus the two header rows
    print(f"wrote {OUT}: {n} agents, {len(content)} bytes")


if __name__ == "__main__":
    main()
