#!/usr/bin/env python3
"""mine_shape_cases.py — extract candidate problem statements from real session transcripts.

Phase 0 of the graph-of-agents refonte needs a labelled problem set to measure
routing against (tasks/graph-of-agents-refonte.md). A7 of
tasks/agent-coverage-roadmap.md requires those cases be MINED from real sessions,
never imagined: a fixture an author invents encodes the router the author already
has in mind, so it cannot falsify that router.

This tool does the mining half ONLY. It emits UNLABELLED candidates. Labelling is
a separate, separately-auditable step, because a miner that also labelled would
decide what counts as a case by the shape it wanted to find — the same
circularity, moved one file earlier.

Determinism (a fixture set that changes between runs cannot be a baseline):
files are traversed in sorted order, case ids are content hashes, and sampling
draws from a seeded PRNG. Same corpus + same seed => byte-identical output.

Every rejected turn is counted under a NAMED reason and the tally is printed to
stderr. A miner that silently drops most of its input reads as "the corpus only
had 40 cases" when it in fact had thousands (rules/coding-standards.md §8).

Provenance: each candidate carries its project, session id, turn uuid, timestamp
and git branch, so any case can be traced back to the turn it came from and the
claim "these are real" is checkable rather than asserted.

Output: JSONL on --out (one candidate object per line).
Exit codes: 0 candidates written, 2 usage error, 3 no candidate survived filtering.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import random
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

# Turn markers that identify machine-generated user turns rather than a human
# problem statement. Each is a literal substring test against the turn text.
# The list is empirical: every entry was added after counting how many turns of
# the corpus it matches, never pre-emptively (a filter with no measured hit rate
# is a guess about the corpus, and would quietly shrink the candidate pool).
_MACHINE_MARKERS = (
    "<command-name>",
    "<local-command-",
    "<system-reminder>",
    "[Request interrupted",
    "<user-prompt-submit-hook>",
    "Caveat: The messages below were generated by the user",
    "<task-notification>",
    "<bash-stdout>",
    "<bash-stderr>",
    "<bash-input>",
)

# Markers that only identify a machine turn when they OPEN it. The context-guard
# checkpoint template is emitted as "Resume from: <path>\nNext action: ...", so an
# anchored test drops the emitted template while keeping a human turn that quotes
# it mid-sentence — 2 of the corpus's 131 "Resume from:" turns are exactly that.
_MACHINE_PREFIXES = (
    "Resume from:",
    "Resume from checkpoint",
    "CHECKPOINT — context cleared",
)

# A turn whose problem is carried by an attached image ("[Image #1] this node
# should be dimmed") cannot be routed from its text: the text alone under-states
# or misstates the problem. Excluded as UNEVALUABLE, not as noise — a router that
# scored badly on these would be failing a question it was never shown.
_ATTACHMENT_MARKER = "[Image #"


@dataclass(frozen=True)
class Limits:
    """Length window a candidate must fall in, in characters.

    Below `min_chars` a turn is an acknowledgement ("ok", "merged both PR"),
    which states no problem to route. Above `max_chars` it is a pasted artefact
    (log, diff, file) rather than a statement. Both bounds are conventions of
    this harness, not measured thresholds, and are recorded as such in the
    manifest so a later run can move them and show the effect.
    """

    min_chars: int
    max_chars: int


def iter_transcript_files(root: Path, excludes: tuple[str, ...]) -> list[Path]:
    """Return every transcript file under `root`, sorted, minus excluded projects.

    Recursive, not one level deep: transcripts sit at <project>/<session>.jsonl but
    also at <project>/<session>/subagents/agent-*.jsonl. Those nested files hold no
    human problem statement — every user turn in them is `isSidechain` — but they
    must still be OPENED and counted, or the drop tally reports a corpus that was
    never read as if it had been filtered (rules/coding-standards.md §8).
    """
    files = sorted(root.rglob("*.jsonl"))
    if not excludes:
        return files
    return [
        f
        for f in files
        if not any(pat in f.relative_to(root).parts[0] for pat in excludes)
    ]


def extract_text(obj: dict) -> str:
    """Return the human-authored text of a transcript turn, or "" if it has none.

    Content is either a plain string or a list of typed parts; only `text` parts
    are human prose. tool_result parts are tool output echoed back into the turn
    and are not authored by the user.
    """
    content = obj.get("message", {}).get("content")
    if isinstance(content, str):
        return content.strip()
    if not isinstance(content, list):
        return ""
    parts = [
        p.get("text", "")
        for p in content
        if isinstance(p, dict) and p.get("type") == "text"
    ]
    return " ".join(parts).strip()


def drop_reason(obj: dict, text: str, limits: Limits) -> str | None:
    """Return the named reason this turn is not a candidate, or None if it is one."""
    if obj.get("type") != "user":
        return "not-a-user-turn"
    if obj.get("isSidechain"):
        return "subagent-turn"
    if obj.get("isMeta"):
        return "meta-turn"
    if not text:
        return "no-text-content"
    if any(marker in text for marker in _MACHINE_MARKERS):
        return "machine-generated-turn"
    if text.startswith(_MACHINE_PREFIXES):
        return "machine-generated-prefix"
    if _ATTACHMENT_MARKER in text:
        return "image-dependent-turn"
    if len(text) < limits.min_chars:
        return "too-short"
    if len(text) > limits.max_chars:
        return "too-long"
    return None


def _normalise(text: str) -> str:
    """Collapse whitespace and case so near-identical restatements dedupe to one."""
    return " ".join(text.lower().split())


def _case_id(text: str) -> str:
    """Content-addressed id: stable across runs, and equal for equal text."""
    return hashlib.sha256(_normalise(text).encode("utf-8")).hexdigest()[:16]


def _candidate(obj: dict, text: str, project: str) -> dict:
    return {
        "case_id": _case_id(text),
        "text": text,
        "chars": len(text),
        "provenance": {
            "project": project,
            "session_id": obj.get("sessionId"),
            "turn_uuid": obj.get("uuid"),
            "timestamp": obj.get("timestamp"),
            "cwd": obj.get("cwd"),
            "git_branch": obj.get("gitBranch"),
        },
    }


def mine(files: list[Path], root: Path, limits: Limits) -> tuple[list[dict], Counter]:
    """Extract deduplicated candidates from `files`, with a tally of drop reasons."""
    candidates: dict[str, dict] = {}
    drops: Counter = Counter()
    for path in files:
        project = path.relative_to(root).parts[0]
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            try:
                obj = json.loads(line)
            except json.JSONDecodeError:
                drops["unparseable-line"] += 1
                continue
            text = extract_text(obj) if obj.get("type") == "user" else ""
            reason = drop_reason(obj, text, limits)
            if reason is not None:
                drops[reason] += 1
                continue
            cand = _candidate(obj, text, project)
            if cand["case_id"] in candidates:
                drops["duplicate-text"] += 1
                continue
            candidates[cand["case_id"]] = cand
    return list(candidates.values()), drops


def read_case_ids(paths: list[Path]) -> set[str]:
    """Collect the case_ids already present in previously-drawn JSONL files.

    Lets a sample be GROWN without redrawing: an existing labelled batch is passed
    back in and the new draw is disjoint from it. Relabelling an already-labelled
    case to enlarge a gold set would be pure waste, and redrawing with a different
    seed would silently discard the labels already paid for.
    """
    seen: set[str] = set()
    for path in paths:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                seen.add(json.loads(line)["case_id"])
    return seen


def sample(candidates: list[dict], count: int, seed: int) -> list[dict]:
    """Draw `count` candidates with a seeded PRNG, ordered by id for stable output.

    Sorting by case_id before drawing removes any dependence on filesystem order,
    so the sample is a function of (corpus, seed) alone.
    """
    ordered = sorted(candidates, key=lambda c: c["case_id"])
    if count <= 0 or count >= len(ordered):
        return ordered
    return sorted(random.Random(seed).sample(ordered, count), key=lambda c: c["case_id"])


def _report(drops: Counter, mined: int, written: int) -> None:
    print("mine_shape_cases: drop tally (named reasons, no silent loss)", file=sys.stderr)
    for reason, n in sorted(drops.items(), key=lambda kv: -kv[1]):
        print(f"  {reason:<24} {n}", file=sys.stderr)
    print(f"  {'candidates mined':<24} {mined}", file=sys.stderr)
    print(f"  {'candidates written':<24} {written}", file=sys.stderr)


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument(
        "--transcripts",
        type=Path,
        default=Path.home() / ".claude" / "projects",
        help="root holding <project>/<session>.jsonl transcripts",
    )
    p.add_argument("--out", type=Path, required=True, help="JSONL output path")
    p.add_argument(
        "--exclude-project",
        action="append",
        default=[],
        metavar="SUBSTRING",
        help="skip projects whose directory name contains SUBSTRING (repeatable)",
    )
    p.add_argument("--min-chars", type=int, default=60)
    p.add_argument("--max-chars", type=int, default=1200)
    p.add_argument(
        "--exclude-ids",
        action="append",
        default=[],
        type=Path,
        metavar="JSONL",
        help="drop candidates whose case_id appears in this earlier draw (repeatable)",
    )
    p.add_argument("--sample", type=int, default=0, help="0 = write every candidate")
    p.add_argument("--seed", type=int, default=20260804, help="sampling PRNG seed")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if not args.transcripts.is_dir():
        print(f"mine_shape_cases: no such directory: {args.transcripts}", file=sys.stderr)
        return 2
    files = iter_transcript_files(args.transcripts, tuple(args.exclude_project))
    limits = Limits(args.min_chars, args.max_chars)
    candidates, drops = mine(files, args.transcripts, limits)
    already = read_case_ids(args.exclude_ids)
    if already:
        kept = [c for c in candidates if c["case_id"] not in already]
        drops["already-drawn"] += len(candidates) - len(kept)
        candidates = kept
    selected = sample(candidates, args.sample, args.seed)
    _report(drops, len(candidates), len(selected))
    if not selected:
        print("mine_shape_cases: no candidate survived filtering", file=sys.stderr)
        return 3
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as fh:
        for cand in selected:
            fh.write(json.dumps(cand, ensure_ascii=False) + "\n")
    print(f"mine_shape_cases: wrote {len(selected)} candidates to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
